from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from .client import AsyncOpenSERP, OpenSERP
from .debug import DebugEvent
from .errors import (
    CaptchaError,
    CloudOnlyError,
    InsufficientCreditsError,
    OssOnlyError,
    RateLimitError,
    SERPError,
    TimeoutError,
)
from .models import (
    Backend,
    BatchExtractBilling,
    BatchExtractItem,
    BatchExtractMeta,
    BatchExtractResult,
    CircuitBreakerStatsResponse,
    CloudAccount,
    CreditInfo,
    Engine,
    EnginesCapabilities,
    EnginesStatus,
    ExtractedContent,
    ExtractHeading,
    ExtractLink,
    ExtractMeta,
    ExtractMode,
    ExtractModeUsed,
    ExtractResult,
    FeatureItem,
    FeatureLink,
    HealthStatus,
    ImageEnvelope,
    ImageResult,
    LastResponse,
    MegaEnginesResponse,
    MegaMode,
    MegaSearchEnvelope,
    Pricing,
    ProxyStats,
    ReadinessStatus,
    ResponseFormat,
    SearchEnvelope,
    SearchResult,
    SerpFeature,
    StatsResponse,
)

try:
    __version__ = _pkg_version("openserp")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "AsyncOpenSERP",
    "Backend",
    "BatchExtractBilling",
    "BatchExtractItem",
    "BatchExtractMeta",
    "BatchExtractResult",
    "CaptchaError",
    "CircuitBreakerStatsResponse",
    "CloudAccount",
    "CloudOnlyError",
    "CreditInfo",
    "DebugEvent",
    "Engine",
    "EnginesCapabilities",
    "EnginesStatus",
    "ExtractHeading",
    "ExtractLink",
    "ExtractMeta",
    "ExtractMode",
    "ExtractModeUsed",
    "ExtractResult",
    "ExtractedContent",
    "FeatureItem",
    "FeatureLink",
    "HealthStatus",
    "ImageEnvelope",
    "ImageResult",
    "InsufficientCreditsError",
    "LastResponse",
    "MegaEnginesResponse",
    "MegaMode",
    "MegaSearchEnvelope",
    "OpenSERP",
    "OssOnlyError",
    "Pricing",
    "ProxyStats",
    "RateLimitError",
    "ReadinessStatus",
    "ResponseFormat",
    "SERPError",
    "SearchEnvelope",
    "SearchResult",
    "SerpFeature",
    "StatsResponse",
    "TimeoutError",
]
